apiVersion: v1
kind: Service
metadata:
  name: demo-app
spec:
  type: {{ .Values.service.type }}
  selector:
    app: demo-app
  ports:
    - name: http
      port: 80
      targetPort: 80
    {{- if .Values.grpc.enabled }}
    - name: grpc
      port: {{ .Values.grpc.port }}
      targetPort: {{ .Values.grpc.port }}
    {{- end }}
